int _putchar(char);
void print_alphabet(void);
void print_alphabt_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void Jack_bauer(void);
void times_tables(void);
int add(int a, int b);
void print_to_98(int n);
void print_times_table(int n);
